version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client" # Location of the client package.json
    schedule:
      interval: "daily" # Can be daily, weekly, or monthly
    ignore:
      - dependency-type: "all" # Ignore all updates except security ones
    allow:
      - dependency-type: "security" # Only security updates